apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-config
spec:
  storageClassName: nfs-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-data
spec:
  storageClassName: nfs-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org.edgexfoundry.service: edgex-core-consul
  name: edgex-core-consul
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      org.edgexfoundry.service: edgex-core-consul
  template:
    metadata:
      labels:
        org.edgexfoundry.service: edgex-core-consul
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/edge
                operator: DoesNotExist
      containers:
      - name: edgex-core-consul
        image: consul:1.10.3
        imagePullPolicy: IfNotPresent
        args: ["agent", "-ui", "-bootstrap", "-server", "-client", "0.0.0.0"]
        volumeMounts:
        - mountPath: /consul/config
          name: consul-config
        - mountPath: /consul/data
          name: consul-data
        ports:
        - containerPort: 8500
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 8500
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 8500
          timeoutSeconds: 1
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      hostname: edgex-core-consul
      restartPolicy: Always
      volumes:
      - name: consul-config
        persistentVolumeClaim:
          claimName: consul-config
      - name: consul-data
        persistentVolumeClaim:
          claimName: consul-data
---
apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: edgex-core-consul
  name: edgex-core-consul
spec:
  type: ClusterIP
  selector:
    org.edgexfoundry.service: edgex-core-consul
  ports:     
  - name: tcp8500
    port: 8500
    targetPort: 8500  
---
apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: edgex-core-consul
  name: edgex-core-consul-nodeport
spec:
  type: NodePort
  selector:
    org.edgexfoundry.service: edgex-core-consul
  ports:     
  - name: tcp8500
    port: 8500
    targetPort: 8500
