apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org.edgexfoundry.service: edgex-core-data
  name: edgex-core-data
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      org.edgexfoundry.service: edgex-core-data
  template:
    metadata:
      labels:
        org.edgexfoundry.service: edgex-core-data
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/edge
                operator: DoesNotExist
      containers:
      - name: edgex-core-data
        image: edgexfoundry/core-data-arm64:2.1.1
        imagePullPolicy: IfNotPresent
        command: ["/core-data", "-cp=consul.http://edgex-core-consul.$(NAMESPACE).svc:8500", "--registry", "--confdir=/res"]
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLIENTS_CORE_COMMAND_HOST
          value: edgex-core-command.$(NAMESPACE).svc
        - name: CLIENTS_CORE_DATA_HOST
          value: edgex-core-data
        - name: CLIENTS_CORE_METADATA_HOST
          value: edgex-core-metadata.$(NAMESPACE).svc
        - name: CLIENTS_SUPPORT_NOTIFICATIONS_HOST
          value: edgex-support-notifications.$(NAMESPACE).svc
        - name: CLIENTS_SUPPORT_SCHEDULER_HOST
          value: edgex-support-scheduler.$(NAMESPACE).svc
        - name: DATABASES_PRIMARY_HOST
          value: edgex-redis.$(NAMESPACE).svc
        - name: EDGEX_SECURITY_SECRET_STORE
          value: "false"
        - name: MESSAGEQUEUE_HOST
          value: edgex-redis.$(NAMESPACE).svc
        - name: REGISTRY_HOST
          value: edgex-core-consul.$(NAMESPACE).svc
        - name: SERVICE_HOST
          value: edgex-core-data
        ports:
        - containerPort: 5563
          protocol: TCP
        - containerPort: 59880
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 59880
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 59880
          timeoutSeconds: 1
        securityContext:
          runAsUser: 2002
          runAsGroup: 2001
      hostname: edgex-core-data
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: edgex-core-data
  name: edgex-core-data
spec:
  type: ClusterIP
  selector:
    org.edgexfoundry.service: edgex-core-data
  ports:     
  - name: tcp5563
    port: 5563
    targetPort: 5563
  - name: tcp59880
    port: 59880
    targetPort: 59880     
