apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org.edgexfoundry.service: edgex-sys-mgmt-agent
  name: edgex-sys-mgmt-agent
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      org.edgexfoundry.service: edgex-sys-mgmt-agent
  template:
    metadata:
      labels:
        org.edgexfoundry.service: edgex-sys-mgmt-agent
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/edge
                operator: DoesNotExist
      containers:
      - name: edgex-sys-mgmt-agent
        image: edgexfoundry/sys-mgmt-agent-arm64:2.1.1
        imagePullPolicy: IfNotPresent
        command: ["/sys-mgmt-agent", "-cp=consul.http://edgex-core-consul.$(NAMESPACE).svc:8500", "--registry", "--confdir=/res"]
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLIENTS_CORE_COMMAND_HOST
          value: edgex-core-command.$(NAMESPACE).svc
        - name: CLIENTS_CORE_DATA_HOST
          value: edgex-core-data.$(NAMESPACE).svc
        - name: CLIENTS_CORE_METADATA_HOST
          value: edgex-core-metadata.$(NAMESPACE).svc
        - name: CLIENTS_SUPPORT_NOTIFICATIONS_HOST
          value: edgex-support-notifications.$(NAMESPACE).svc
        - name: CLIENTS_SUPPORT_SCHEDULER_HOST
          value: edgex-support-scheduler.$(NAMESPACE).svc
        - name: DATABASES_PRIMARY_HOST
          value: edgex-redis.$(NAMESPACE).svc
        - name: EDGEX_SECURITY_SECRET_STORE
          value: "false"
        - name: EXECUTORPATH
          value: /sys-mgmt-executor
        - name: METRICSMECHANISM
          value: executor
        - name: REGISTRY_HOST
          value: edgex-core-consul.$(NAMESPACE).svc
        - name: SERVICE_HOST
          value: edgex-sys-mgmt-agent        
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker
        ports:
        - containerPort: 58890
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 58890
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 58890
          timeoutSeconds: 1
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      hostname: edgex-sys-mgmt-agent
      restartPolicy: Always
      volumes:
      - name: docker
        hostPath:
          path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: edgex-sys-mgmt-agent
  name: edgex-sys-mgmt-agent
spec:
  type: ClusterIP
  selector:
    org.edgexfoundry.service: edgex-sys-mgmt-agent
  ports:  
  - name: tcp58890
    port: 58890
    targetPort: 58890     
