apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org.edgexfoundry.service: edgex-security-secretstore-setup
  name: edgex-security-secretstore-setup
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      org.edgexfoundry.service: edgex-security-secretstore-setup
  template:
    metadata:
      labels:
        org.edgexfoundry.service: edgex-security-secretstore-setup
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/edge
                operator: DoesNotExist
      initContainers:
      - name: edgex-security-bootstrapper-init
        image: edgexfoundry/security-bootstrapper-arm64:2.1.1
        command: ["/bin/sh","-c","cp -pr /edgex-init/* /edgex-init-share/"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /edgex-init-share
          name: edgex-init-share
      containers:
      - name: edgex-security-secretstore-setup
        image: edgexfoundry/security-secretstore-setup-arm64:2.1.1
        imagePullPolicy: IfNotPresent
        command: ["/usr/bin/dumb-init"]
        args: ["/bin/sh", "-x", "/entrypoint.sh"]
        envFrom:
        - configMapRef:
            name: edgex-config
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: STAGEGATE_SECRETSTORESETUP_HOST
          value: edgex-security-secretstore-setup
        volumeMounts:
        - mountPath: /edgex-init
          name: edgex-init-share
        - mountPath: /run
          name: tmpfs-run
        - mountPath: /vault
          name: vault
        - mountPath: /tmp/edgex/secrets
          name: edgex-secrets
        - mountPath: /tmp/kong
          name: kong
        - mountPath: /tmp/kuiper
          name: kuiper-sources
        - mountPath: /tmp/kuiper-connections
          name: kuiper-connections
        - mountPath: /vault/config
          name: vault-config 
        ports:
        - containerPort: 54322
          protocol: TCP
        securityContext:
          runAsUser: 0
      hostname: edgex-security-secretstore-setup
      restartPolicy: Always
      volumes:
      - name: edgex-init-share
        emptyDir: {}
      - name: tmpfs-run
        emptyDir:
          medium: Memory
      - name: vault
        hostPath:
          path: /data/vault
          type: DirectoryOrCreate    
      - name: edgex-secrets
        hostPath:
          path: /tmp/edgex/secrets
          type: DirectoryOrCreate
      - name: kong
        hostPath:
          path: /tmp/kong
          type: DirectoryOrCreate
      - name: kuiper-sources
        hostPath:
          path: /tmp/kuiper
          type: DirectoryOrCreate
      - name: kuiper-connections
        hostPath:
          path: /tmp/kuiper-connections
          type: DirectoryOrCreate
      - name: vault-config
        hostPath:
          path: /vault/config
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: edgex-security-secretstore-setup
  name: edgex-security-secretstore-setup
spec:
  type: ClusterIP
  selector:
    org.edgexfoundry.service: edgex-security-secretstore-setup
  ports:
  - name: tcp54322
    port: 54322
    targetPort: 54322      

