apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: edgex-jakarta
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2022-12-16T09:54:47Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
    org.edgexfoundry.service: edgex-core-command
  name: edgex-core-command
  namespace: default
  resourceVersion: "620025"
  uid: e8bcb349-2abd-4828-a201-b296a0119287
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      org.edgexfoundry.service: edgex-core-command
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        org.edgexfoundry.service: edgex-core-command
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/edge
                operator: DoesNotExist
      containers:
      - env:
        - name: Service_Host
          value: edgex-core-command
        envFrom:
        - configMapRef:
            name: edgex-core-command-config
        image: edgexfoundry/core-command-arm64:2.1.1
        imagePullPolicy: IfNotPresent
        command: 
        - /core-command
        - -cp=consul.http://edgex-core-consul.default.svc.cluster.local:8500
        - --registry
        - --confdir=/res
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/v1/ping
            port: 48082
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        name: edgex-core-command
        ports:
        - containerPort: 48082
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/v1/ping
            port: 48082
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostname: edgex-core-command
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
