apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-config-pv
spec:
  storageClassName: {{ .Values.storage.core.consul.class }}
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.core.consul.configSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-data-pv
spec:
  storageClassName: {{ .Values.storage.core.consul.class }}
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.core.consul.dataSize }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org.edgexfoundry.service: edgex-core-consul
  name: edgex-core-consul
spec:
  replicas: 1
  selector:
    matchLabels:
      org.edgexfoundry.service: edgex-core-consul
  template:
    metadata:
      labels:
        org.edgexfoundry.service: edgex-core-consul
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/edge
                {{- if .Values.edgex.affinity.core.consul.edgeNode }}
                operator: Exists
                {{- else }}
                operator: DoesNotExist
                {{- end }}
      containers:
      - name: edgex-core-consul
        image: {{ .Values.edgex.image.core.consul }}
        imagePullPolicy: IfNotPresent
        args: ["agent", "-ui", "-bootstrap", "-server", "-client", "0.0.0.0"]
        volumeMounts:
        - mountPath: /consul/config
          name: consul-config
        - mountPath: /consul/data
          name: consul-data
        ports:
        - containerPort: 8500
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 8500
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 8500
          timeoutSeconds: 1
        {{- if .Values.edgex.resources.core.consul.enforceLimits }}
        resources:
          limits:
            memory: {{ .Values.edgex.resources.core.consul.limits.memory }}
            cpu: {{ .Values.edgex.resources.core.consul.limits.cpu }}
          requests:
            memory: {{ .Values.edgex.resources.core.consul.requests.memory }}
            cpu: {{ .Values.edgex.resources.core.consul.requests.cpu }}
        {{- end}}
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      hostname: edgex-core-consul
      restartPolicy: Always
      volumes:
      - name: consul-config
        persistentVolumeClaim:
          claimName: consul-config-pv
      - name: consul-data
        persistentVolumeClaim:
          claimName: consul-data-pv
---
apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: edgex-core-consul
  name: edgex-core-consul
spec:
  type: {{ .Values.expose.core.consul.type }}
  selector:
    org.edgexfoundry.service: edgex-core-consul
  ports:     
  - name: tcp8500
    port: 8500
    targetPort: 8500
    {{- if .Values.expose.core.consul.nodePort }}
    nodePort: {{ .Values.expose.core.consul.nodePort }}
    {{- end}}
