apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org.edgexfoundry.service: edgex-device-virtual
  name: edgex-device-virtual
spec:
  replicas: {{ .Values.edgex.replicas.device.virtual }}
  selector:
    matchLabels:
      org.edgexfoundry.service: edgex-device-virtual
  template:
    metadata:
      labels:
        org.edgexfoundry.service: edgex-device-virtual
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/edge
                {{- if .Values.edgex.affinity.device.virtual.edgeNode }}
                operator: Exists
                {{- else }}
                operator: DoesNotExist
                {{- end }}
      containers:
      - name: edgex-device-virtual
        image: {{ .Values.edgex.image.device.virtual }}
        imagePullPolicy: IfNotPresent
        command: ["/device-virtual", "-cp=consul.http://edgex-core-consul.$(NAMESPACE).svc:8500", "--registry", "--confdir=/res"]
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLIENTS_CORE_COMMAND_HOST
          value: edgex-core-command.$(NAMESPACE).svc
        - name: CLIENTS_CORE_DATA_HOST
          value: edgex-core-data.$(NAMESPACE).svc
        - name: CLIENTS_CORE_METADATA_HOST
          value: edgex-core-metadata.$(NAMESPACE).svc
        - name: CLIENTS_SUPPORT_NOTIFICATIONS_HOST
          value: edgex-support-notifications.$(NAMESPACE).svc
        - name: CLIENTS_SUPPORT_SCHEDULER_HOST
          value: edgex-support-scheduler.$(NAMESPACE).svc
        - name: DATABASES_PRIMARY_HOST
          value: edgex-redis.$(NAMESPACE).svc
        - name: EDGEX_SECURITY_SECRET_STORE
          value: "false"
        - name: MESSAGEQUEUE_HOST
          value: edgex-redis.$(NAMESPACE).svc
        - name: REGISTRY_HOST
          value: edgex-core-consul.$(NAMESPACE).svc
        - name: SERVICE_HOST
          value: edgex-device-virtual
        ports:
        - containerPort: 59900
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 59900
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 59900
          timeoutSeconds: 1
        {{- if .Values.edgex.resources.device.virtual.enforceLimits }}
        resources:
          limits:
            memory: {{ .Values.edgex.resources.device.virtual.limits.memory }}
            cpu: {{ .Values.edgex.resources.device.virtual.limits.cpu }}
          requests:
            memory: {{ .Values.edgex.resources.device.virtual.requests.memory }}
            cpu: {{ .Values.edgex.resources.device.virtual.requests.cpu }}
        {{- end}}
        securityContext:
          runAsUser: 2002
          runAsGroup: 2001
      hostname: edgex-device-virtual
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: edgex-device-virtual
  name: edgex-device-virtual
spec:
  type: {{ .Values.expose.device.virtual.type }}
  selector:
    org.edgexfoundry.service: edgex-device-virtual
  ports:  
  - name: tcp59900
    port: 59900
    targetPort: 59900
    {{- if .Values.expose.device.virtual.nodePort }}
    nodePort: {{ .Values.expose.device.virtual.nodePort }}
    {{- end}}    
